/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/ /Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.util.List;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Constants;
import model.circuit.Circuit;
import model.circuit.CircuitEuc;
import model.circuit.CircuitGeo;
import model.coord.CoordEuc;
import model.coord.CoordGeo;
import view.waypoint.Waypoint;
import view.waypoint.WaypointEuc;
import view.waypoint.WaypointGeo;

/**
 *
 * @author ugola
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        Waypoint.loadImage();
        initComponents();
        tableModel = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        distanceTable.setModel(tableModel);
        distanceTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        mainPane.resetToPreferredSizes();
        sidePanel.resetToPreferredSizes();
        
        mapEuc.addWaypointSelectionListener(waypoint -> {
            switch (actionMode) {
                case SELECT:
                    CoordEuc coord = (CoordEuc) waypoint.getCoord();
                    idValueField.setText(String.valueOf(coord.getId()));
                    firstCompField.setText(String.format("%.3f", coord.getX()));
                    secondCompField.setText(String.format("%.3f", coord.getY()));
                    break;
                    
                case REMOVE:
                    mapEuc.removeCoord((WaypointEuc) waypoint);                    
            }
        });
        
        mapGeo.addWaypointSelectionListener(waypoint -> {
            switch (actionMode) {
                case SELECT:
                    CoordGeo coord = (CoordGeo) waypoint.getCoord();
                    idValueField.setText(String.valueOf(coord.getId()));
                    firstCompField.setText(String.format("%.3f", coord.getDecimalLatitude()));
                    secondCompField.setText(String.format("%.3f", coord.getDecimalLongitude()));
                    break;
                    
                case REMOVE:
                    mapGeo.removeCoord((WaypointGeo) waypoint);                    
            }
        });
        
        mapEuc.addMapClickedListener(e -> {
            if (SwingUtilities.isLeftMouseButton(e) && actionMode == actionMode.ADD) {
                mapEuc.addCoord(e);
            }
        });
        
        mapGeo.addMapClickedListener(e -> {
            if (SwingUtilities.isLeftMouseButton(e) &&actionMode == actionMode.ADD) {
                mapGeo.addCoord(e);
            }
        });
        
        actionMode = actionMode.SELECT;
    }
    
    enum ActionMode {
        SELECT,
        ADD,
        REMOVE
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPane = new javax.swing.JSplitPane();
        layeredPane = new javax.swing.JLayeredPane();
        toolBar = new javax.swing.JPanel();
        selectToolBt = new javax.swing.JButton();
        addToolBt = new javax.swing.JButton();
        removeToolBt = new javax.swing.JButton();
        mapGeo = new view.MapGeo();
        mapEuc = new view.MapEuc();
        zoomLabelPanel = new javax.swing.JPanel();
        scaleLabel = new java.awt.Label();
        sidePanel = new javax.swing.JSplitPane();
        tabbedPane = new javax.swing.JTabbedPane();
        algorithmPanel = new javax.swing.JPanel();
        randomButton = new javax.swing.JButton();
        greedyButton = new javax.swing.JButton();
        insertionButton = new javax.swing.JButton();
        generationButton = new javax.swing.JButton();
        ameliorationButton = new javax.swing.JButton();
        distancePanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        distanceTable = new javax.swing.JTable();
        detailsPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        firstCompLabel = new javax.swing.JLabel();
        secondCompLabel = new javax.swing.JLabel();
        firstCompField = new javax.swing.JTextField();
        secondCompField = new javax.swing.JTextField();
        idValueField = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openFileMenuItem = new javax.swing.JMenuItem();
        closeFileMenuItem = new javax.swing.JMenuItem();
        saveFileItem = new javax.swing.JMenuItem();
        saveAsFileItem = new javax.swing.JMenuItem();
        exportResultFileItem = new javax.swing.JMenuItem();
        windowMenu = new javax.swing.JMenu();
        resetMenuItem = new javax.swing.JMenuItem();
        displayDistanceItem = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fête des Lumières");

        mainPane.setDividerLocation(700);
        mainPane.setResizeWeight(0.7);

        selectToolBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/select_tool.png"))); // NOI18N
        selectToolBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectToolBtActionPerformed(evt);
            }
        });
        toolBar.add(selectToolBt);

        addToolBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/add_tool.png"))); // NOI18N
        addToolBt.setToolTipText("");
        addToolBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToolBtActionPerformed(evt);
            }
        });
        toolBar.add(addToolBt);

        removeToolBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/remove_tool.png"))); // NOI18N
        removeToolBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeToolBtActionPerformed(evt);
            }
        });
        toolBar.add(removeToolBt);

        mapGeo.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                mapGeoMouseWheelMoved(evt);
            }
        });

        mapEuc.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                mapEucMouseWheelMoved(evt);
            }
        });

        zoomLabelPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scaleLabel.setAlignment(java.awt.Label.CENTER);
        scaleLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        scaleLabel.setText("x 1.0");

        javax.swing.GroupLayout zoomLabelPanelLayout = new javax.swing.GroupLayout(zoomLabelPanel);
        zoomLabelPanel.setLayout(zoomLabelPanelLayout);
        zoomLabelPanelLayout.setHorizontalGroup(
            zoomLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
            .addGroup(zoomLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scaleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
        );
        zoomLabelPanelLayout.setVerticalGroup(
            zoomLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(zoomLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scaleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scaleLabel.getAccessibleContext().setAccessibleParent(layeredPane);

        layeredPane.setLayer(toolBar, javax.swing.JLayeredPane.PALETTE_LAYER);
        layeredPane.setLayer(mapGeo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(mapEuc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(zoomLabelPanel, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(layeredPane);
        layeredPane.setLayout(layeredPaneLayout);
        layeredPaneLayout.setHorizontalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(605, Short.MAX_VALUE))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mapGeo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mapEuc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                    .addGap(0, 601, Short.MAX_VALUE)
                    .addComponent(zoomLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layeredPaneLayout.setVerticalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(576, Short.MAX_VALUE))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mapGeo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mapEuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                    .addGap(0, 596, Short.MAX_VALUE)
                    .addComponent(zoomLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mainPane.setLeftComponent(layeredPane);

        sidePanel.setDividerLocation(325);
        sidePanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        sidePanel.setResizeWeight(0.6);
        sidePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        randomButton.setText("Aleatoire");
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });

        greedyButton.setText("Glouton");
        greedyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greedyButtonActionPerformed(evt);
            }
        });

        insertionButton.setText("Insertion");
        insertionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertionButtonActionPerformed(evt);
            }
        });

        generationButton.setText("Generation");
        generationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generationButtonActionPerformed(evt);
            }
        });

        ameliorationButton.setText("Amelioration");
        ameliorationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ameliorationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout algorithmPanelLayout = new javax.swing.GroupLayout(algorithmPanel);
        algorithmPanel.setLayout(algorithmPanelLayout);
        algorithmPanelLayout.setHorizontalGroup(
            algorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algorithmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(algorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomButton)
                    .addComponent(greedyButton)
                    .addComponent(insertionButton)
                    .addComponent(generationButton)
                    .addComponent(ameliorationButton))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        algorithmPanelLayout.setVerticalGroup(
            algorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algorithmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(randomButton)
                .addGap(18, 18, 18)
                .addComponent(greedyButton)
                .addGap(18, 18, 18)
                .addComponent(insertionButton)
                .addGap(29, 29, 29)
                .addComponent(generationButton)
                .addGap(30, 30, 30)
                .addComponent(ameliorationButton)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Algorithmes", algorithmPanel);

        distanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableScrollPane.setViewportView(distanceTable);

        javax.swing.GroupLayout distancePanelLayout = new javax.swing.GroupLayout(distancePanel);
        distancePanel.setLayout(distancePanelLayout);
        distancePanelLayout.setHorizontalGroup(
            distancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        distancePanelLayout.setVerticalGroup(
            distancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Tableau des distances", distancePanel);

        sidePanel.setLeftComponent(tabbedPane);
        tabbedPane.getAccessibleContext().setAccessibleName("tabbedPane");

        detailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Détails du lieu"));
        detailsPanel.setName("Détails"); // NOI18N
        detailsPanel.setLayout(new java.awt.GridBagLayout());

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLabel.setText("ID :");
        idLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        detailsPanel.add(idLabel, gridBagConstraints);

        firstCompLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstCompLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstCompLabel.setText("X :");
        firstCompLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        detailsPanel.add(firstCompLabel, gridBagConstraints);

        secondCompLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        secondCompLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondCompLabel.setText("Y :");
        secondCompLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        detailsPanel.add(secondCompLabel, gridBagConstraints);

        firstCompField.setEditable(false);
        firstCompField.setColumns(6);
        firstCompField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstCompField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstCompField.setText("0");
        firstCompField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        firstCompField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCompFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        detailsPanel.add(firstCompField, gridBagConstraints);

        secondCompField.setEditable(false);
        secondCompField.setColumns(6);
        secondCompField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        secondCompField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        secondCompField.setText("0");
        secondCompField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        detailsPanel.add(secondCompField, gridBagConstraints);

        idValueField.setEditable(false);
        idValueField.setColumns(6);
        idValueField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        idValueField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idValueField.setText("0");
        idValueField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        detailsPanel.add(idValueField, gridBagConstraints);

        sidePanel.setRightComponent(detailsPanel);

        mainPane.setRightComponent(sidePanel);

        fileMenu.setText("Fichier");

        openFileMenuItem.setText("Ouvrir une carte");
        openFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openFileMenuItem);

        closeFileMenuItem.setText("Fermer la carte");
        closeFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(closeFileMenuItem);

        saveFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveFileItem.setText("Enregistrer");
        saveFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveFileItem);

        saveAsFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveAsFileItem.setText("Enregistrer sous");
        saveAsFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsFileItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsFileItem);

        exportResultFileItem.setText("Exporter fichier résultat");
        exportResultFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportResultFileItemActionPerformed(evt);
            }
        });
        fileMenu.add(exportResultFileItem);

        menuBar.add(fileMenu);

        windowMenu.setText("Affichage");

        resetMenuItem.setText("Réinitialiser");
        resetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMenuItemActionPerformed(evt);
            }
        });
        windowMenu.add(resetMenuItem);

        displayDistanceItem.setSelected(true);
        displayDistanceItem.setText("Afficher les distances");
        displayDistanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDistanceItemActionPerformed(evt);
            }
        });
        windowMenu.add(displayDistanceItem);

        menuBar.add(windowMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileMenuItemActionPerformed
        JFileChooser selectionWindow = new JFileChooser();
        selectionWindow.showOpenDialog(this);

        if (selectionWindow.getSelectedFile() != null) {
            String path = selectionWindow.getSelectedFile().getAbsolutePath();
            String type = Circuit.getFileType(path);
            closeMap();

            int coordsCount;
            String[] columnsNames;

            switch (type) {
                case "EUC_2D":
                    currentCircuitEuc = new CircuitEuc();
                    currentCircuitEuc.loadFile(selectionWindow.getSelectedFile());
                    mapEuc.open(currentCircuitEuc);
                    SwingUtilities.invokeLater(() -> {
                        if (mapGeo != null)
                            if (mapGeo.isVisible()) {
                                mapGeo.setVisible(false);
                            }
                        
                        mapEuc.setVisible(true);
                        mainPane.repaint();
                    });

                    // Modification de la distanceTable
                    coordsCount = currentCircuitEuc.getCoords().size();
                    // Création des noms de colonnes
                    columnsNames = new String[coordsCount + 1];
                    columnsNames[0] = ""; // coin vide
                    for (int i = 0; i < coordsCount; i++) {
                        columnsNames[i + 1] = "Lieu " + (i + 1);
                    }

                    tableModel.setDataVector(currentCircuitEuc.createDistanceMatrix(), columnsNames);
                    
                    // Modification du panneau des détails
                    firstCompLabel.setText("X :");
                    secondCompLabel.setText("Y :");
                    
                    break;

                case "GEO":
                    currentCircuitGeo = new CircuitGeo();
                    currentCircuitGeo.loadFile(selectionWindow.getSelectedFile());
                    mapGeo.open(currentCircuitGeo);
                    SwingUtilities.invokeLater(() -> {
                        if (mapEuc != null)
                            if (mapEuc.isVisible()) {
                                mapEuc.setVisible(false);
                            }
                        
                        mapGeo.setVisible(true);
                        mainPane.repaint();
                    });
                    
                    // Modification de la distanceTable
                    coordsCount = currentCircuitGeo.getCoords().size();
                    // Création des noms de colonnes
                    columnsNames = new String[coordsCount + 1];
                    columnsNames[0] = ""; // coin vide
                    for (int i = 0; i < coordsCount; i++) {
                        columnsNames[i + 1] = "Lieu " + (i + 1);
                    }

                    tableModel.setDataVector(currentCircuitGeo.createDistanceMatrix(), columnsNames);
                    
                    // Modification du panneau des détails
                    firstCompLabel.setText("Latitude :");
                    secondCompLabel.setText("Longitude :");
                    
                    break;
                    
                default: JOptionPane.showMessageDialog(this, "Le type de fichier n'est pas pris en charge", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openFileMenuItemActionPerformed

    private void closeFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFileMenuItemActionPerformed
        closeMap();
    }//GEN-LAST:event_closeFileMenuItemActionPerformed

    private void mapEucMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_mapEucMouseWheelMoved
        scaleLabel.setText("x " + String.format("%.1f", mapEuc.getScale()));
    }//GEN-LAST:event_mapEucMouseWheelMoved

    private void resetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMenuItemActionPerformed
        mainPane.resetToPreferredSizes();
        sidePanel.resetToPreferredSizes();
    }//GEN-LAST:event_resetMenuItemActionPerformed

    private void mapGeoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_mapGeoMouseWheelMoved
        scaleLabel.setText("x " + String.format("%.1f", mapGeo.getScale()));
    }//GEN-LAST:event_mapGeoMouseWheelMoved

    private void firstCompFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCompFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstCompFieldActionPerformed

    private void greedyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greedyButtonActionPerformed
        if (mapEuc.isOpen()) {
            currentCircuitEuc.bestGreedyAlgorithm();
            mapEuc.repaint();
        }
        else if (mapGeo.isOpen()) {
            currentCircuitGeo.bestGreedyAlgorithm();
            mapGeo.repaint();
        }
        else {
            JOptionPane.showMessageDialog(mainPane, "Aucun fichier n'a été ouvert", "Erreur d'ouverture", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_greedyButtonActionPerformed

    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        if (mapEuc.isOpen()) {
            currentCircuitEuc.randomAlgorithm();
            mapEuc.repaint();
        }
        else if (mapGeo.isOpen()) {
            currentCircuitGeo.randomAlgorithm();
            mapGeo.repaint();
        }
        else {
            JOptionPane.showMessageDialog(mainPane, "Aucun fichier n'a été ouvert", "Erreur d'ouverture", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_randomButtonActionPerformed

    private void selectToolBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectToolBtActionPerformed
        actionMode = ActionMode.SELECT;
    }//GEN-LAST:event_selectToolBtActionPerformed

    private void insertionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertionButtonActionPerformed
        if (mapEuc.isOpen()) {
            currentCircuitEuc.bestInsertionAlgorithm();
            System.out.println("Longueur : " + currentCircuitEuc.calculateCircuitLength(currentCircuitEuc.getInsertionCircuit()));
            mapEuc.repaint();
        }
        else if (mapGeo.isOpen()) {
            currentCircuitGeo.bestInsertionAlgorithm();
            mapGeo.repaint();
        }
        else {
            JOptionPane.showMessageDialog(mainPane, "Aucun fichier n'a été ouvert", "Erreur d'ouverture", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_insertionButtonActionPerformed

    private void addToolBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToolBtActionPerformed
        actionMode = ActionMode.ADD;
    }//GEN-LAST:event_addToolBtActionPerformed

    private void removeToolBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeToolBtActionPerformed
        actionMode = ActionMode.REMOVE;
    }//GEN-LAST:event_removeToolBtActionPerformed

    private void displayDistanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDistanceItemActionPerformed
        Constants.DISPLAY_DISTANCE = !Constants.DISPLAY_DISTANCE;
        mainPane.repaint();
    }//GEN-LAST:event_displayDistanceItemActionPerformed

    private void exportResultFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportResultFileItemActionPerformed
        JFileChooser inputChooser = new JFileChooser();
        inputChooser.setMultiSelectionEnabled(true);
        int result = inputChooser.showOpenDialog(this);
        File[] files = inputChooser.getSelectedFiles();
        
        if (result == JFileChooser.APPROVE_OPTION) {
            JFileChooser outputChooser = new JFileChooser();
            outputChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            outputChooser.setMultiSelectionEnabled(false);
            outputChooser.showOpenDialog(this);

            if (outputChooser.getSelectedFile() != null) {
                String outputFilePath = outputChooser.getSelectedFile().getAbsolutePath();
                Circuit.exportResultFile(files, outputFilePath);
                JOptionPane.showMessageDialog(this, "Le fichier de résultat a été exporté", "Fichier résultat", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_exportResultFileItemActionPerformed

    private void saveFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileItemActionPerformed
        boolean success = false;
        
        if (mapEuc.isOpen()) success = currentCircuitEuc.saveFile();
        else if (mapGeo.isOpen()) success = currentCircuitGeo.saveFile();

        if (success) 
            JOptionPane.showMessageDialog(this, "Le fichier a bien été sauvegardé", "Fichier sauvegardé", JOptionPane.PLAIN_MESSAGE);
        else {
            if (!mapGeo.isOpen() && !mapEuc.isOpen())
                JOptionPane.showMessageDialog(this, "Aucun fichier ouvert à sauvegarder", "Erreur", JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "Erreur lors de la sauvegarde", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveFileItemActionPerformed

    private void saveAsFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsFileItemActionPerformed
        if (mapEuc.isOpen() || mapGeo.isOpen()) {            
            JFileChooser chooser = new JFileChooser();
            int result = chooser.showSaveDialog(this);
            
            if (result == JFileChooser.APPROVE_OPTION) {
                boolean success = false;
                
                File selectedFile = chooser.getSelectedFile();
                
                if (mapEuc.isOpen()) success = currentCircuitEuc.saveFileAs(selectedFile);
                else success = currentCircuitGeo.saveFileAs(selectedFile);

                if (success) 
                    JOptionPane.showMessageDialog(this, "Le fichier a bien été sauvegardé", "Fichier sauvegardé", JOptionPane.PLAIN_MESSAGE);
                else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de la sauvegarde", "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Aucun fichier ouvert à sauvegarder", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveAsFileItemActionPerformed

    private void generationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generationButtonActionPerformed
        // TODO add your handling code here:
        String message = "Entrez le nombre de lieux que vous voulez générer !" ;
        String reponseStr = JOptionPane.showInputDialog(mainPane, message, "Génération", JOptionPane.PLAIN_MESSAGE);
        int reponse = 0;

        if (reponseStr != null) { // Vérifie si l'utilisateur n'a pas annulé
            try {
                reponse = Integer.parseInt(reponseStr); // Convertit la chaîne en entier
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(mainPane, "Veuillez entrer un nombre valide.", "Erreur", JOptionPane.ERROR_MESSAGE);
                return; // Ou une autre gestion d'erreur
            }
        } else {
            return; // Annulé par l'utilisateur
        }
        Random random = new Random();

        for (int i = 1; i <= reponse; i++) {
            double x = 10 + (200 - 10) * random.nextDouble();
            double y = 10 + (200 - 10) * random.nextDouble();
            if (mapEuc.isOpen()) {
                CoordEuc coord1 = new CoordEuc(x, y) ;
                WaypointEuc w = new WaypointEuc(coord1) ;
                mapEuc.addWaypoint(coord1);
                currentCircuitEuc.addCoord(coord1);
            }
            else if (mapGeo.isOpen()) {
                CoordGeo coord1 = new CoordGeo(x, y) ;
                WaypointGeo w = new WaypointGeo(coord1) ;
                mapGeo.addWaypoint(coord1);
                mapGeo.addWaypoint(coord1);
                currentCircuitGeo.addCoord(coord1);
            }
            else {
                 JOptionPane.showMessageDialog(mainPane, "Aucun fichier n'a été ouvert", "Erreur d'ouverture", JOptionPane.ERROR_MESSAGE);
            }
        }    
    }//GEN-LAST:event_generationButtonActionPerformed

    private void ameliorationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ameliorationButtonActionPerformed
        // TODO add your handling code here:
        if (mapEuc.isOpen()) {
            currentCircuitEuc.bestGreedyAlgorithm();
            List<CoordEuc> circuit = currentCircuitEuc.getGreedyCircuit() ;
            currentCircuitEuc.ameliorerCircuitParEchange(circuit);
            List<CoordEuc> circuitAm = currentCircuitEuc.getAmeliorateCircuit();
            
            System.out.println("Longueur : " + currentCircuitEuc.calculateCircuitLength(circuit));
            System.out.println("Longueur : " + currentCircuitEuc.calculateCircuitLength(circuitAm));
            
            mapEuc.repaint();
        }
        
        
        else if (mapGeo.isOpen()) {
            currentCircuitGeo.bestGreedyAlgorithm();
            List<CoordGeo> circuit = currentCircuitGeo.getGreedyCircuit() ;
            currentCircuitGeo.ameliorerCircuitParEchange(circuit);
            List<CoordGeo> circuitAm = currentCircuitGeo.getAmeliorateCircuit();
            
            System.out.println("Longueur  du circuit initial : " + currentCircuitGeo.calculateCircuitLength(circuit));
            System.out.println("Longueur après amélioration: " + currentCircuitGeo.calculateCircuitLength(circuitAm));
            
            mapGeo.repaint();
            
        }
        else {
            JOptionPane.showMessageDialog(mainPane, "Aucun fichier n'a été ouvert", "Erreur d'ouverture", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ameliorationButtonActionPerformed
    
    public void closeMap() {
        if (mapGeo.isOpen()) {
            mapGeo.close();
        }

        if (mapEuc.isOpen()) {
            mapEuc.close();
        }
        tableModel.setColumnCount(0);
        tableModel.setRowCount(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }
    
    private CircuitEuc currentCircuitEuc;
    private CircuitGeo currentCircuitGeo;
    private DefaultTableModel tableModel ;
    private ActionMode actionMode;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToolBt;
    private javax.swing.JPanel algorithmPanel;
    private javax.swing.JButton ameliorationButton;
    private javax.swing.JMenuItem closeFileMenuItem;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JRadioButtonMenuItem displayDistanceItem;
    private javax.swing.JPanel distancePanel;
    private javax.swing.JTable distanceTable;
    private javax.swing.JMenuItem exportResultFileItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextField firstCompField;
    private javax.swing.JLabel firstCompLabel;
    private javax.swing.JButton generationButton;
    private javax.swing.JButton greedyButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idValueField;
    private javax.swing.JButton insertionButton;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JSplitPane mainPane;
    private view.MapEuc mapEuc;
    private view.MapGeo mapGeo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openFileMenuItem;
    private javax.swing.JButton randomButton;
    private javax.swing.JButton removeToolBt;
    private javax.swing.JMenuItem resetMenuItem;
    private javax.swing.JMenuItem saveAsFileItem;
    private javax.swing.JMenuItem saveFileItem;
    private java.awt.Label scaleLabel;
    private javax.swing.JTextField secondCompField;
    private javax.swing.JLabel secondCompLabel;
    private javax.swing.JButton selectToolBt;
    private javax.swing.JSplitPane sidePanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JPanel toolBar;
    private javax.swing.JMenu windowMenu;
    private javax.swing.JPanel zoomLabelPanel;
    // End of variables declaration//GEN-END:variables
}
